// <auto-generated />
using System;
using API_DONACIONES.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_DONACIONES.Migrations
{
    [DbContext(typeof(DonacionesDbContext))]
    [Migration("20260730205546_migracion")]
    partial class migracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("API_DONACIONES.Entities.DonationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime>("DonationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("DonationDate");

                    b.Property<string>("DonnorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("donor_id");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_by_id");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_date");

                    b.Property<bool>("NeedsRefrigeration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("needs_refrigeration");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<string>("TypeFood")
                        .HasColumnType("TEXT")
                        .HasColumnName("type_food");

                    b.HasKey("Id");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("API_DONACIONES.Entities.DonorEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_number");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_id");

                    b.Property<string>("DNI")
                        .HasColumnType("TEXT")
                        .HasColumnName("dni");

                    b.Property<string>("DonorType")
                        .HasColumnType("TEXT")
                        .HasColumnName("donor_type");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_by_id");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Donators");
                });
#pragma warning restore 612, 618
        }
    }
}
